# Generated by Django 3.2.13 on 2024-02-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'On the way'), (3, 'Delivered')], default=0),
        ),
    ]
